language: ruby
 
script: "bundle exec rspec"
rvm:
  - 2.0
  - 2.1
  - 2.2
  - ruby-head

notifications:
  email:
    recipients:
      - stan001212@gmail.com
    on_failure: change
    on_success: never
